//!#import global.g_discord_gml_buf in dbuf
//!#import buffer.* in Buffer
//!#import buffer_get_address in Buffer.ptr
//!#import buffer_bool in BT.bool
//!#import buffer_u8 in BT.byte
//!#import buffer_u16 in BT.short
//!#import buffer_u32 in BT.uint
//!#import buffer_s32 in BT.int32
//!#import buffer_string in BT.string
//!#import buffer_f64 in BT.real
//!#import buffer_u64 in BT.int64
//!#import pointer_null in nullptr
//!#import discord_result_ok in an_ok
//!#import discord_glue_int64_buf in int64buf
//!#import discord_glue_int64_ptr in int64ptr
//!#import discord_glue_read_value in resval